spring:
  datasource:
    password: Kita@2018
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/springcloudfornecedor
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
